WORKER_HWM = 2

# Testcard constants
TESTCARD_FPS = 30
TESTCARD_ANGLE_STEP = 3
DEGREES_IN_CIRCLE = 360

# Handler constants
BUFFER_HANDLER_MISS_SLEEP = 0.001  # seconds
DISPLAY_WAITKEY_TIMEOUT = 1  # milliseconds
ESC_KEY_CODE = 27
DISPFPS_DEFAULT_N = 100
FPS_TEXT_POSITION = (50, 50)  # (x, y)
FPS_TEXT_FONT_SCALE = 1
FPS_TEXT_LINE_THICKNESS = 2
FPS_TEXT_COLOR = (0, 255, 0)  # Green in BGR format
