QUALITY = 50

STOPSTREAM = -1
FRAMEMISS = -2
TRACKMISS = -3

COLLECT_TIMESTEP = 0.01
DEC_TIMESTEP = 0.01
DIST_TIMESTEP = 0.01
ENC_TIMESTEP = 0.01
PUB_TIMESTEP = 0.01
SUB_TIMESTEP = 0.01
REQ_TIMESTEP = 0.03

# Encoder constants
STOPSTREAM_DUMMY_FRAME_SIZE = 10
STOPSTREAM_SLEEP_SECONDS = 1

COLLECT_HWM = 3
DEC_HWM = 3
ENC_HWM = 3
DIST_HWM = 3
PUB_HWM = 3
SUB_HWM = 3
REQ_HWM = 3

# Async requester constants
ASYNC_STOP_SLEEP_SECONDS = 0.1
